name: use-action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  use-action:

    runs-on: macos-latest

    steps:
    - uses: paulz/prepare-macos@main
    - run: echo Complete
